version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  database:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  laravel:
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    tty: true
    depends_on:
      - database
